version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  backend:
    build:
      context: ./backend 
    image: my-node-app
    ports:
      - "13000:3000"
  frontend:
    build:
      context: ./frontend 
    ports:
      - "3001:3000"
    depends_on:
      - backend